# wrangler.toml (Corrected Version)

name = "pigmap"
main = "src/index.js"
compatibility_date = "2024-06-01"
compatibility_flags = ["nodejs_compat"]

# ┃▶ ROUTES & DOMAINS
# Use a routes table to direct traffic from your domains to this Worker.
routes = [
  { pattern = "pigmap.org/*", zone_name = "pigmap.org" },
  { pattern = "www.pigmap.org/*", zone_name = "pigmap.org" },
  { pattern = "kc.pigmap.org/*", zone_name = "pigmap.org" },
  { pattern = "kcmo.pigmap.org/*", zone_name = "pigmap.org" },
  { pattern = "kansascity.pigmap.org/*", zone_name = "pigmap.org" }
]

# ┃▶ STATIC ASSETS
# The [site] block efficiently handles serving static files from your "public" directory.
[site]
bucket = "./public"

# ┃▶ SERVICE BINDINGS
[[d1_databases]]
binding = "LIVESTOCK_DB"
database_name = "livestock-db"
database_id = "11a70f2e-831a-4fdc-8447-d891fdf950b7"

[[r2_buckets]]
binding = "LIVESTOCK_MEDIA"
bucket_name = "livestock-media"

[[kv_namespaces]]
binding = "PIGMAP_CONFIG"
id = "96dd87122a134b75a59e94a106d2b9ac"

[[durable_objects.bindings]]
name = "LIVESTOCK_REPORTS"
class_name = "LivestockReport"

# This defines an in-Worker rate limiter binding.
[[unsafe.bindings]]
name = "RATE_LIMITER" # This is the name used in the code (env.RATE_LIMITER)
type = "ratelimit"
# A unique integer for this rule within your account. You can just make one up.
namespace_id = "333"
# The actual limit: 20 requests per 60 seconds.
simple = { limit = 20, period = 60 }

# ┃▶ MIGRATIONS
[[migrations]]
tag = "v1"
new_classes = ["LivestockReport"]

# ┃▶ OBSERVABILITY
[observability.logs]
enabled = true
