# PigMap.org Cloudflare Worker Configuration

name = "pigmap"
main = "src/index.js"
compatibility_date = "2024-06-01"

workers_dev = true  # Enable the workers.dev subdomain for development
routes = [
  # Main domain routes
  { pattern = "pigmap.org/*", zone_name = "pigmap.org" },
  { pattern = "www.pigmap.org/*", zone_name = "pigmap.org" },
  { pattern = "media.pigmap.org/*", zone_name = "pigmap.org" },
  
  # Kansas City specific routes
  { pattern = "kc.pigmap.org/*", zone_name = "pigmap.org" },
  { pattern = "kcmo.pigmap.org/*", zone_name = "pigmap.org" },
  { pattern = "kansascity.pigmap.org/*", zone_name = "pigmap.org" }
]

# R2 Bucket for Media Storage
[[r2_buckets]]
binding = "LIVESTOCK_MEDIA"
bucket_name = "livestock-media"

# KV Namespace for Configuration
[[kv_namespaces]]
binding = "PIGMAP_CONFIG"
id = "96dd87122a134b75a59e94a106d2b9ac"

# D1 Database for Reports
[[d1_databases]]
binding = "LIVESTOCK_DB"
database_name = "livestock"
database_id = "11a70f2e-831a-4fdc-8447-d891fdf950b7"

# Durable Object for real-time updates
[[durable_objects.bindings]]
name = "LIVESTOCK_REPORTS"
class_name = "LivestockReport"

[[migrations]]
tag = "v1"
new_classes = ["LivestockReport"]

# Assets binding for static files
[assets]
directory = "./public"
binding = "ASSETS"
# Set SPA handling to improve asset routing behavior
not_found_handling = "single-page-application"
# Ensure everything passes through the worker first to set proper MIME types
run_worker_first = true

# Enable observability logs
[observability.logs]
enabled = true
