// src/i18n.js

export const languageNames = {
  en: "English", es: "Español", ht: "Kreyòl Ayisyen", zh: "中文", vi: "Tiếng Việt",
  ar: "العربية", am: "አማርኛ", sw: "Kiswahili", so: "Soomaali", fa: "فارسی",
  fr: "Français", ne: "नेपाली", kar: "Karen", my: "မြန်မာဘာသာ", pt: "Português",
  ur: "اردو", ku: "Kurdî"
};

export const translations = {
    am: { add_new_marker: "አዲስ ምልክት ማድረጊያ ያክሉ", save: "አስቀምጥ", cancel: "ሰርዝ", edit: "አርትዕ", delete: "ሰርዝ", add_marker_instruction: "ምልክት ለማከል ካርታው ላይ ጠቅ ያድርጉ። Esc ለመሰረዝ ይጫኑ።", marker_added: "ምልክቱ በተሳካ ሁኔታ ታክሏል!", marker_updated: "ምልክቱ ተዘምኗል!", marker_deleted: "ምልክቱ ተሰርዟል።", comments: "አስተያየቶች", add_comment: "አስተያየት ያክሉ", author: "ስም", confirm_delete: "ይህንን ምልክት ለመሰረዝ እርግጠኛ ነዎት?", label_type: "አይነት", label_description: "መግለጫ", label_count: "ስንት?", label_icon: "ምልክት አዶ", cat_sighting: "ሲጠን", cat_tracks: "ምልክቶች / ማስረጃ", cat_damaged_fence: "ስብሮ ሰብቆ", cat_unusual_activity: "ያልተለመደ ሁኔታ", cat_equipment: "የተጣለ ዕቃ", cat_other: "ሌላ" },
    ar: { add_new_marker: "إضافة علامة جديدة", save: "حفظ", cancel: "إلغاء", edit: "تعديل", delete: "حذف", add_marker_instruction: "انقر على الخريطة لوضع تقريرك. اضغط Esc للإلغاء.", marker_added: "تمت إضافة العلامة بنجاح!", marker_updated: "تم تحديث التقرير!", marker_deleted: "تم حذف العلامة.", comments: "تعليقات", add_comment: "إضافة تعليق", author: "الاسم", confirm_delete: "هل أنت متأكد أنك تريد حذف هذه العلامة؟", label_type: "النوع", label_description: "الوصف", label_count: "كم عدد؟", label_icon: "أيقونة العلامة", cat_sighting: "مشاهدة", cat_tracks: "آثار / أدلة", cat_damaged_fence: "سياج تالف", cat_unusual_activity: "نشاط غير عادي", cat_equipment: "معدات مهجورة", cat_other: "أخرى" },
    en: { add_new_marker: "Add New Marker", save: "Save", cancel: "Cancel", edit: "Edit", delete: "Delete", add_marker_instruction: "Click on the map to place your report. Press Esc to cancel.", marker_added: "Marker added successfully!", marker_updated: "Report updated!", marker_deleted: "Marker deleted.", comments: "Comments", add_comment: "Add Comment", author: "Name", confirm_delete: "Are you sure you want to delete this marker?", label_type: "Type", label_description: "Description", label_count: "How many?", label_icon: "Marker Icon", cat_sighting: "Sighting", cat_tracks: "Tracks / Evidence", cat_damaged_fence: "Damaged Fence", cat_unusual_activity: "Unusual Activity", cat_equipment: "Abandoned Equipment", cat_other: "Other" },
    es: { add_new_marker: "Agregar Nuevo Marcador", save: "Guardar", cancel: "Cancelar", edit: "Editar", delete: "Eliminar", add_marker_instruction: "Haz clic en el mapa para colocar tu reporte. Presiona Esc para cancelar.", marker_added: "¡Marcador agregado con éxito!", marker_updated: "¡Reporte actualizado!", marker_deleted: "Marcador eliminado.", comments: "Comentarios", add_comment: "Agregar Comentario", author: "Nombre", confirm_delete: "¿Estás seguro de que quieres eliminar este marcador?", label_type: "Tipo", label_description: "Descripción", label_count: "¿Cuántos?", label_icon: "Icono del Marcador", cat_sighting: "Avistamiento", cat_tracks: "Rastros / Evidencia", cat_damaged_fence: "Valla Dañada", cat_unusual_activity: "Actividad Inusual", cat_equipment: "Equipo Abandonado", cat_other: "Otro" },
    fa: { add_new_marker: "نشانگر جدید اضافه کنید", save: "ذخیره", cancel: "لغو", edit: "ویرایش", delete: "حذف", add_marker_instruction: "برای قرار دادن گزارش روی نقشه کلیک کنید. برای لغو Esc را فشار دهید.", marker_added: "نشانگر با موفقیت اضافه شد!", marker_updated: "گزارش به‌روزرسانی شد!", marker_deleted: "نشانگر حذف شد.", comments: "نظرات", add_comment: "افزودن نظر", author: "نام", confirm_delete: "آیا از حذف این نشانگر مطمئن هستید؟", label_type: "نوع", label_description: "توضیح", label_count: "چند تا؟", label_icon: "آیکون نشانگر", cat_sighting: "مشاهده", cat_tracks: "ردپا / شواهد", cat_damaged_fence: "حصار آسیب‌دیده", cat_unusual_activity: "فعالیت غیرعادی", cat_equipment: "تجهیزات رها شده", cat_other: "سایر" },
    fr: { add_new_marker: "Ajouter un Nouveau Marqueur", save: "Sauvegarder", cancel: "Annuler", edit: "Éditer", delete: "Supprimer", add_marker_instruction: "Cliquez sur la carte pour placer votre signalement. Appuyez sur Esc pour annuler.", marker_added: "Marqueur ajouté avec succès !", marker_updated: "Signalement mis à jour !", marker_deleted: "Marqueur supprimé.", comments: "Commentaires", add_comment: "Ajouter un commentaire", author: "Nom", confirm_delete: "Êtes-vous sûr de vouloir supprimer ce marqueur ?", label_type: "Type", label_description: "Description", label_count: "Combien ?", label_icon: "Icône du Marqueur", cat_sighting: "Observation", cat_tracks: "Traces / Preuves", cat_damaged_fence: "Clôture Endommagée", cat_unusual_activity: "Activité Suspecte", cat_equipment: "Équipement Abandonné", cat_other: "Autre" },
    ht: { add_new_marker: "Ajoute Nouvo Makè", save: "Sere", cancel: "Anile", edit: "Edite", delete: "Efase", add_marker_instruction: "Klike sou kat la pou plase rapò ou. Peze Esc pou anile.", marker_added: "Makè ajoute avèk siksè!", marker_updated: "Rapò aktualize!", marker_deleted: "Makè efase.", comments: "Kòmantè", add_comment: "Ajoute yon kòmantè", author: "Non", confirm_delete: "Èske ou sèten ou vle efase makè sa a?", label_type: "Kalite", label_description: "Deskripsyon", label_count: "Konbyen?", label_icon: "Ikòn Makè", cat_sighting: "Obsèvasyon", cat_tracks: "Tras / Prèv", cat_damaged_fence: "Klòti Kase", cat_unusual_activity: "Aktivite Inhabityèl", cat_equipment: "Ekipman Abandone", cat_other: "Lòt" },
    kar: { add_new_marker: "တၢ်ပနီၣ်တခါထီၣ်", save: "ဘၣ်", cancel: "တဘၣ်", edit: "မၤ", delete: "မၤလီၤ", add_marker_instruction: "Click on the map to place your report. Press Esc to cancel.", marker_added: "Marker added successfully!", marker_updated: "Report updated!", marker_deleted: "Marker deleted.", comments: "Comments", add_comment: "Add Comment", author: "Name", confirm_delete: "Are you sure you want to delete this marker?", label_type: "Type", label_description: "Description", label_count: "How many?", label_icon: "Marker Icon", cat_sighting: "Sighting", cat_tracks: "Tracks / Evidence", cat_damaged_fence: "Damaged Fence", cat_unusual_activity: "Unusual Activity", cat_equipment: "Abandoned Equipment", cat_other: "Other" },
    ku: { add_new_marker: "Nîşankerek Nû lê zêde bike", save: "Tomar bike", cancel: "Betal bike", edit: "Weşandin", delete: "Jêbirin", add_marker_instruction: "Ji bo danîna raporê li nexşeyê bikirtînin. Ji bo betal kirinê Esc bikirtînin.", marker_added: "Nîşanker bi serkeftî hate zêdekirin!", marker_updated: "Rapor hat nûkirin!", marker_deleted: "Nîşanker hate jêbirin.", comments: "Şîrove", add_comment: "Şîroveyekê lê zêde bike", author: "Nav", confirm_delete: "Ma hûn guman dikin ku hûn dixwazin vê nîşankerê jêbirin?", label_type: "Cure", label_description: "Danasîn", label_count: "Çend?", label_icon: "Nîşana Nîşankerê", cat_sighting: "Dîtbarî", cat_tracks: "Şop / Delîl", cat_damaged_fence: "Êvaz Zirarditin", cat_unusual_activity: "Çalakiya Nebaş", cat_equipment: "Amûrên Terk kirî", cat_other: "Din" },
    my: { add_new_marker: "အမှတ်အသားအသစ်ထည့်ပါ", save: "သိမ်းဆည်း", cancel: "မလုပ်တော့", edit: "ပြုပြင်ရန်", delete: "ဖျက်ရန်", add_marker_instruction: "မြေပုံပေါ်တွင် ကလစ်နှိပ်ပါ။ ပယ်ဖျက်ရန် Esc နှိပ်ပါ။", marker_added: "အမှတ်အသားကို အောင်မြင်စွာထည့်ပြီးပါပြီ။", marker_updated: "အစီရင်ခံစာ ပြင်ဆင်ပြီးပါပြီ။", marker_deleted: "အမှတ်အသားကို ဖျက်လိုက်ပါပြီ။", comments: "မှတ်ချက်များ", add_comment: "မှတ်ချက်ထည့်ပါ", author: "အမည်", confirm_delete: "ဤအမှတ်အသားကို ဖျက်လိုကြောင်း သေချာပါသလား။", label_type: "အမျိုးအစား", label_description: "ဖော်ပြချက်", label_count: "ဘယ်နှစ်ကောင်?", label_icon: "မတ်ကာ အိုင်ကွန်", cat_sighting: "တွေ့ရှိမှု", cat_tracks: "လမ်းကြောင်း / သက်သေ", cat_damaged_fence: "ပျက်စီးသောဆားကာ", cat_unusual_activity: "ထူးဆန်းသောလှုပ်ရှားမှု", cat_equipment: "စွန့်ပစ်ထားသောကိရိယာ", cat_other: "အခြား" },
    ne: { add_new_marker: "नयाँ मार्कर थप्नुहोस्", save: "सेभ गर्नुहोस्", cancel: "रद्द गर्नुहोस्", edit: "सम्पादन गर्नुहोस्", delete: "मेटाउनुहोस्", add_marker_instruction: "आफ्नो रिपोर्ट राख्न नक्सामा क्लिक गर्नुहोस्। रद्द गर्न Esc थिच्नुहोस्।", marker_added: "मार्कर सफलतापूर्वक थपियो!", marker_updated: "रिपोर्ट अद्यावधिक गरियो!", marker_deleted: "मार्कर मेटाइयो।", comments: "टिप्पणीहरू", add_comment: "टिप्पणी थप्नुहोस्", author: "नाम", confirm_delete: "के तपाइँ यो मार्कर मेटाउन निश्चित हुनुहुन्छ?", label_type: "प्रकार", label_description: "विवरण", label_count: "कति?", label_icon: "मार्कर आइकन", cat_sighting: "देखाइ", cat_tracks: "ट्र्याक / प्रमाण", cat_damaged_fence: "क्षतिग्रस्त बार", cat_unusual_activity: "असामान्य गतिविधि", cat_equipment: "परित्यक्त उपकरण", cat_other: "अन्य" },
    pt: { add_new_marker: "Adicionar Novo Marcador", save: "Salvar", cancel: "Cancelar", edit: "Editar", delete: "Excluir", add_marker_instruction: "Clique no mapa para posicionar seu relatório. Pressione Esc para cancelar.", marker_added: "Marcador adicionado com sucesso!", marker_updated: "Relatório atualizado!", marker_deleted: "Marcador excluído.", comments: "Comentários", add_comment: "Adicionar Comentário", author: "Nome", confirm_delete: "Tem certeza de que deseja excluir este marcador?", label_type: "Tipo", label_description: "Descrição", label_count: "Quantos?", label_icon: "Ícone do Marcador", cat_sighting: "Avistamento", cat_tracks: "Rastros / Evidências", cat_damaged_fence: "Cerca Danificada", cat_unusual_activity: "Atividade Incomum", cat_equipment: "Equipamento Abandonado", cat_other: "Outro" },
    so: { add_new_marker: "Ku dar Calaamad Cusub", save: "Kaydi", cancel: "Jooji", edit: "Tafatir", delete: "Tirtir", add_marker_instruction: "Guji khariidadda si aad u geysato warbixintaada. Riix Esc si aad u baajiso.", marker_added: "Calaamadda si guul leh ayaa loogu daray!", marker_updated: "Warbixintii waa la cusbooneysiiyey!", marker_deleted: "Calaamadda waa la tirtiray.", comments: "Faallooyin", add_comment: "Faallo ku dar", author: "Magac", confirm_delete: "Ma hubtaa inaad rabto inaad tirtirto calaamaddan?", label_type: "Nooca", label_description: "Sharraxaadda", label_count: "Imisa?", label_icon: "Astaanta Calaamadda", cat_sighting: "Aragtida", cat_tracks: "Raadka / Caddaynta", cat_damaged_fence: "Xariga Burburay", cat_unusual_activity: "Hawsha Aan Caadiga Ahayn", cat_equipment: "Qalab la Tegey", cat_other: "Kale" },
    sw: { add_new_marker: "Ongeza Alama Mpya", save: "Hifadhi", cancel: "Ghairi", edit: "Hariri", delete: "Futa", add_marker_instruction: "Bofya kwenye ramani kuweka ripoti yako. Bonyeza Esc kufuta.", marker_added: "Alama imeongezwa kwa mafanikio!", marker_updated: "Ripoti imesasishwa!", marker_deleted: "Alama imefutwa.", comments: "Maoni", add_comment: "Ongeza Maoni", author: "Jina", confirm_delete: "Una uhakika unataka kufuta alama hii?", label_type: "Aina", label_description: "Maelezo", label_count: "Wangapi?", label_icon: "Ikoni ya Alama", cat_sighting: "Kuonekana", cat_tracks: "Nyayo / Ushahidi", cat_damaged_fence: "Uzio Ulioharibiwa", cat_unusual_activity: "Shughuli ya Ajabu", cat_equipment: "Vifaa Vilivyoachwa", cat_other: "Nyingine" },
    ur: { add_new_marker: "نیا مارکر شامل کریں", save: "محفوظ کریں", cancel: "منسوخ کریں", edit: "ترمیم", delete: "حذف کریں", add_marker_instruction: "رپورٹ رکھنے کے لیے نقشے پر کلک کریں۔ منسوخ کرنے کے لیے Esc دبائیں۔", marker_added: "مارکر کامیابی سے شامل ہو گیا!", marker_updated: "رپورٹ اپ ڈیٹ ہو گئی!", marker_deleted: "مارکر حذف کر دیا گیا۔", comments: "تبصرے", add_comment: "تبصرہ شامل کریں", author: "نام", confirm_delete: "کیا آپ واقعی اس مارکر کو حذف کرنا چاہتے ہیں؟", label_type: "قسم", label_description: "تفصیل", label_count: "کتنے؟", label_icon: "مارکر آئیکن", cat_sighting: "دیدار", cat_tracks: "پٹریاں / ثبوت", cat_damaged_fence: "خراب باڑ", cat_unusual_activity: "غیر معمولی سرگرمی", cat_equipment: "چھوڑا ہوا سامان", cat_other: "دیگر" },
    vi: { add_new_marker: "Thêm điểm đánh dấu mới", save: "Lưu", cancel: "Hủy", edit: "Chỉnh sửa", delete: "Xóa", add_marker_instruction: "Nhấp vào bản đồ để đặt báo cáo. Nhấn Esc để hủy.", marker_added: "Đã thêm điểm đánh dấu thành công!", marker_updated: "Đã cập nhật báo cáo!", marker_deleted: "Đã xóa điểm đánh dấu.", comments: "Bình luận", add_comment: "Thêm bình luận", author: "Tên", confirm_delete: "Bạn có chắc chắn muốn xóa điểm đánh dấu này không?", label_type: "Loại", label_description: "Mô tả", label_count: "Bao nhiêu?", label_icon: "Biểu tượng đánh dấu", cat_sighting: "Quan sát", cat_tracks: "Dấu vết / Bằng chứng", cat_damaged_fence: "Hàng rào hư hỏng", cat_unusual_activity: "Hoạt động bất thường", cat_equipment: "Thiết bị bỏ rơi", cat_other: "Khác" },
    zh: { add_new_marker: "添加新标记", save: "保存", cancel: "取消", edit: "编辑", delete: "删除", add_marker_instruction: "点击地图放置报告。按Esc取消。", marker_added: "标记添加成功！", marker_updated: "报告已更新！", marker_deleted: "标记已删除。", comments: "评论", add_comment: "添加评论", author: "姓名", confirm_delete: "您确定要删除此标记吗？", label_type: "类型", label_description: "描述", label_count: "几只?", label_icon: "标记图标", cat_sighting: "目击", cat_tracks: "踪迹/证据", cat_damaged_fence: "受损围栏", cat_unusual_activity: "异常活动", cat_equipment: "废弃设备", cat_other: "其他" }
};
