// src/i18n.js

export const languageNames = {
  en: "English", es: "Español", ht: "Kreyòl Ayisyen", zh: "中文", vi: "Tiếng Việt",
  ar: "العربية", am: "አማርኛ", sw: "Kiswahili", so: "Soomaali", fa: "فارسی",
  fr: "Français", ne: "नेपाली", kar: "Karen", my: "မြန်မာဘာသာ", pt: "Português",
  ur: "اردو", ku: "Kurdî"
};

export const translations = {
    am: { add_new_marker: "አዲስ ምልክት ማድረጊያ ያክሉ", save: "አስቀምጥ", cancel: "ሰርዝ", edit: "አርትዕ", delete: "ሰርዝ", add_marker_instruction: "ምልክት ለማከል ካርታው ላይ ጠቅ ያድርጉ", marker_added: "ምልክቱ በተሳካ ሁኔታ ታክሏል!", marker_deleted: "ምልክቱ ተሰርዟል።", comments: "አስተያየቶች", add_comment: "አስተያየት ያክሉ", author: "ስም", confirm_delete: "ይህንን ምልክት ለመሰረዝ እርግጠኛ ነዎት?" },
    ar: { add_new_marker: "إضافة علامة جديدة", save: "حفظ", cancel: "إلغاء", edit: "تعديل", delete: "حذف", add_marker_instruction: "انقر على الخريطة لإضافة علامة", marker_added: "تمت إضافة العلامة بنجاح!", marker_deleted: "تم حذف العلامة.", comments: "تعليقات", add_comment: "إضافة تعليق", author: "الاسم", confirm_delete: "هل أنت متأكد أنك تريد حذف هذه العلامة؟" },
    en: { add_new_marker: "Add New Marker", save: "Save", cancel: "Cancel", edit: "Edit", delete: "Delete", add_marker_instruction: "Click on the map to add a marker", marker_added: "Marker added successfully!", marker_deleted: "Marker deleted.", comments: "Comments", add_comment: "Add Comment", author: "Name", confirm_delete: "Are you sure you want to delete this marker?" },
    es: { add_new_marker: "Agregar Nuevo Marcador", save: "Guardar", cancel: "Cancelar", edit: "Editar", delete: "Eliminar", add_marker_instruction: "Haga clic en el mapa para agregar un marcador", marker_added: "¡Marcador agregado con éxito!", marker_deleted: "Marcador eliminado.", comments: "Comentarios", add_comment: "Agregar Comentario", author: "Nombre", confirm_delete: "¿Estás seguro de que quieres eliminar este marcador?" },
    fa: { add_new_marker: "نشانگر جدید اضافه کنید", save: "ذخیره", cancel: "لغو", edit: "ویرایش", delete: "حذف", add_marker_instruction: "برای افزودن نشانگر روی نقشه کلیک کنید", marker_added: "نشانگر با موفقیت اضافه شد!", marker_deleted: "نشانگر حذف شد.", comments: "نظرات", add_comment: "افزودن نظر", author: "نام", confirm_delete: "آیا از حذف این نشانگر مطمئن هستید؟" },
    fr: { add_new_marker: "Ajouter un Nouveau Marqueur", save: "Sauvegarder", cancel: "Annuler", edit: "Éditer", delete: "Supprimer", add_marker_instruction: "Cliquez sur la carte pour ajouter un marqueur", marker_added: "Marqueur ajouté avec succès !", marker_deleted: "Marqueur supprimé.", comments: "Commentaires", add_comment: "Ajouter un commentaire", author: "Nom", confirm_delete: "Êtes-vous sûr de vouloir supprimer ce marqueur ?" },
    ht: { add_new_marker: "Ajoute Nouvo Makè", save: "Sere", cancel: "Anile", edit: "Edite", delete: "Efase", add_marker_instruction: "Klike sou kat la pou ajoute yon makè", marker_added: "Makè ajoute avèk siksè!", marker_deleted: "Makè efase.", comments: "Kòmantè", add_comment: "Ajoute yon kòmantè", author: "Non", confirm_delete: "Èske ou sèten ou vle efase makè sa a?" },
    kar: { add_new_marker: "တၢ်ပနီၣ်တခါထီၣ်", save: "ဘၣ်", cancel: "တဘၣ်", edit: "မၤ", delete: "မၤလီၤ", add_marker_instruction: "Click on the map to add a marker", marker_added: "Marker added successfully!", marker_deleted: "Marker deleted.", comments: "Comments", add_comment: "Add Comment", author: "Name", confirm_delete: "Are you sure you want to delete this marker?" },
    ku: { add_new_marker: "Nîşankerek Nû lê zêde bike", save: "Tomar bike", cancel: "Betal bike", edit: "Weşandin", delete: "Jêbirin", add_marker_instruction: "Ji bo lê zêdekirina nîşankerê li ser nexşeyê bikirtînin", marker_added: "Nîşanker bi serkeftî hate zêdekirin!", marker_deleted: "Nîşanker hate jêbirin.", comments: "Şîrove", add_comment: "Şîroveyekê lê zêde bike", author: "Nav", confirm_delete: "Ma hûn guman dikin ku hûn dixwazin vê nîşankerê jêbirin?" },
    my: { add_new_marker: "အမှတ်အသားအသစ်ထည့်ပါ", save: "သိမ်းဆည်း", cancel: "မလုပ်တော့", edit: "ပြုပြင်ရန်", delete: "ဖျက်ရန်", add_marker_instruction: "အမှတ်အသားထည့်ရန် မြေပုံပေါ်တွင် နှိပ်ပါ", marker_added: "အမှတ်အသားကို အောင်မြင်စွာထည့်ပြီးပါပြီ။", marker_deleted: "အမှတ်အသားကို ဖျက်လိုက်ပါပြီ။", comments: "မှတ်ချက်များ", add_comment: "မှတ်ချက်ထည့်ပါ", author: "အမည်", confirm_delete: "ဤအမှတ်အသားကို ဖျက်လိုကြောင်း သေချာပါသလား။" },
    ne: { add_new_marker: "नयाँ मार्कर थप्नुहोस्", save: "सेभ गर्नुहोस्", cancel: "रद्द गर्नुहोस्", edit: "सम्पादन गर्नुहोस्", delete: "मेटाउनुहोस्", add_marker_instruction: "मार्कर थप्न नक्सामा क्लिक गर्नुहोस्", marker_added: "मार्कर सफलतापूर्वक थपियो!", marker_deleted: "मार्कर मेटाइयो।", comments: "टिप्पणीहरू", add_comment: "टिप्पणी थप्नुहोस्", author: "नाम", confirm_delete: "के तपाइँ यो मार्कर मेटाउन निश्चित हुनुहुन्छ?" },
    pt: { add_new_marker: "Adicionar Novo Marcador", save: "Salvar", cancel: "Cancelar", edit: "Editar", delete: "Excluir", add_marker_instruction: "Clique no mapa para adicionar um marcador", marker_added: "Marcador adicionado com sucesso!", marker_deleted: "Marcador excluído.", comments: "Comentários", add_comment: "Adicionar Comentário", author: "Nome", confirm_delete: "Tem certeza de que deseja excluir este marcador?" },
    so: { add_new_marker: "Ku dar Calaamad Cusub", save: "Kaydi", cancel: "Jooji", edit: "Tafatir", delete: "Tirtir", add_marker_instruction: "Guji khariidadda si aad calaamad ugu darto", marker_added: "Calaamadda si guul leh ayaa loogu daray!", marker_deleted: "Calaamadda waa la tirtiray.", comments: "Faallooyin", add_comment: "Faallo ku dar", author: "Magac", confirm_delete: "Ma hubtaa inaad rabto inaad tirtirto calaamaddan?" },
    sw: { add_new_marker: "Ongeza Alama Mpya", save: "Hifadhi", cancel: "Ghairi", edit: "Hariri", delete: "Futa", add_marker_instruction: "Bofya kwenye ramani ili kuongeza alama", marker_added: "Alama imeongezwa kwa mafanikio!", marker_deleted: "Alama imefutwa.", comments: "Maoni", add_comment: "Ongeza Maoni", author: "Jina", confirm_delete: "Una uhakika unataka kufuta alama hii?" },
    ur: { add_new_marker: "نیا مارکر شامل کریں", save: "محفوظ کریں", cancel: "منسوخ کریں", edit: "ترمیم", delete: "حذف کریں", add_marker_instruction: "مارکر شامل کرنے کے لیے نقشے پر کلک کریں", marker_added: "مارکر کامیابی سے شامل ہو گیا!", marker_deleted: "مارکر حذف کر دیا گیا۔", comments: "تبصرے", add_comment: "تبصرہ شامل کریں", author: "نام", confirm_delete: "کیا آپ واقعی اس مارکر کو حذف کرنا چاہتے ہیں؟" },
    vi: { add_new_marker: "Thêm điểm đánh dấu mới", save: "Lưu", cancel: "Hủy", edit: "Chỉnh sửa", delete: "Xóa", add_marker_instruction: "Nhấp vào bản đồ để thêm điểm đánh dấu", marker_added: "Đã thêm điểm đánh dấu thành công!", marker_deleted: "Đã xóa điểm đánh dấu.", comments: "Bình luận", add_comment: "Thêm bình luận", author: "Tên", confirm_delete: "Bạn có chắc chắn muốn xóa điểm đánh dấu này không?" },
    zh: { add_new_marker: "添加新标记", save: "保存", cancel: "取消", edit: "编辑", delete: "删除", add_marker_instruction: "在地图上单击以添加标记", marker_added: "标记添加成功！", marker_deleted: "标记已删除。", comments: "评论", add_comment: "添加评论", author: "姓名", confirm_delete: "您确定要删除此标记吗？" }
};
