name: Deploy PigMap.org

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      - run: npm ci
      - name: Copy library files for client
        run: |
          mkdir -p public/lib
          # Copy OpenLayers
          cp -r node_modules/ol public/lib/
          # Copy GSAP
          mkdir -p public/lib/gsap
          cp -r node_modules/gsap/dist/* public/lib/gsap/
          # Copy ES Module Shims
          cp node_modules/es-module-shims/dist/es-module-shims.js public/lib/
          # Create RBush module
          echo 'import RBush from "rbush"; export default RBush;' > public/lib/rbush.js
      - name: Deploy to Cloudflare
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          command: deploy
